### ISSUE TITLE
Wywołanie WykopAPI.tag_entries(tag) zwraca błąd: "Invalid POST params, Invalid params"

### ISSUE THREAD

**Issue by RadCraftplay** [krasnoludkolo/wykop-sdk-reborn#77]
```text
Traceback (most recent call last):
  File "skrypt.py", line 18, in <module>
    entries = api.tag_entries(tag)
  File ".../wykop/api/client.py", line 383, in tag_entries
    return self.request('Tags', 'Entries',
  File ".../wykop/api/client.py", line 31, in request
    return self.__requestor.request(rtype, rmethod=rmethod,
  File ".../wykop/core/requestor.py", line 54, in request
    return self.parser.parse_response(response)
  File ".../wykop/core/parsers/base.py", line 22, in parse_response
    raise self._resolve_exception(wykop.api.exceptions.base.InvalidParamsError: b'Invalid POST params, Invalid params'
```

Wartość ```tag``` nie jest ```null``` i jest nazwą istniejącego tagu.

Wersja pakietu __wykop-sdk-reborn__: 0.9.4

**Comment by krasnoludkolo** [comment]
hej, możesz pokazać kod? Bo odpaliłem własnie
```
api = WykopAPI("xxx")

api.authenticate(login="xxx", password="xxxx")

print(api.tag("f1"))
```
i normalnie dostałem wynik

**Comment by RadCraftplay** [comment]
Próbowałem zrobić mniej więcej jak w ostatnim przykładzie [tu](https://github.com/krasnoludkolo/wykop-sdk-reborn/wiki/Przyk%C5%82ady).
```python
api = WykopAPI(key, secret)
entries = api.tag_entries(tag)
```

**Comment by RadCraftplay** [comment]
Nevermind metoda działa prawidłowo. Jednak użyłem nieprawidłowego tagu. Wybacz, że zmarnowałem ci czas
